services:
  isbn_ruby_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: isbn_ruby
    container_name: isbn_ruby_container
    command: /bin/bash
    tty: true
    ports:
      - "3000:3000"
    mem_limit: 512mb
